# expert training
EXPERT_LR = 3e-4
EXPERT_BATCH_SIZE = 64
EXPERT_EPOCHS = 5


# reinforcement learning
ACTOR_LR = 1e-4
CRITIC_LR = 1e-4
ENTROPY_LOSS_COEF = 0.1
DISCOUNT_FACTOR = 0.9
GRAD_NORM_CLIP = 1.
OPT_EPOCHS = 5
HORIZON = 4096
BATCH_SIZE = 256
MAX_SAMPLES = 3.0e7 #2.5
INIT_ACTION_STD = 0.5


# simulation settings
STEP_TIME = 0.12
FRAME_SKIP = 3
TIMEOUT = 1000
VISUALIZATION_TIMEOUT = 200


# agent properties
AGENT_RADIUS = 0.1
PREFERRED_SPEED = 1.3
MAX_SPEED = 2.5
NEIGHBORHOOD_RADIUS = 5.

# obstacle observation
ONLY_NEAREST = False
OBSERVED_POINTS = 60